//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTA_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTA_Manager.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string buttonOpen {
            get {
                return ResourceManager.GetString("buttonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offline Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboBoxOffline {
            get {
                return ResourceManager.GetString("comboBoxOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Online Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboBoxOnline {
            get {
                return ResourceManager.GetString("comboBoxOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string labelDisabled {
            get {
                return ResourceManager.GetString("labelDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string labelEnabled {
            get {
                return ResourceManager.GetString("labelEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot make changes while GTA V is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageChanges {
            get {
                return ResourceManager.GetString("MessageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot close launcher while GTA V is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageClose {
            get {
                return ResourceManager.GetString("MessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rage not found! Make sure it is installed correctly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRage {
            get {
                return ResourceManager.GetString("MessageRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove selected scripts? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRemove {
            get {
                return ResourceManager.GetString("MessageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes will not take effect until next launch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRestart {
            get {
                return ResourceManager.GetString("MessageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTA V is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRunning {
            get {
                return ResourceManager.GetString("MessageRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create shortcut to desktop? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageShortcut {
            get {
                return ResourceManager.GetString("MessageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTA V not found! Make sure launcher is in GTA V root directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string textBoxDirectory {
            get {
                return ResourceManager.GetString("textBoxDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rage not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleRage {
            get {
                return ResourceManager.GetString("TitleRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleRemove {
            get {
                return ResourceManager.GetString("TitleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleRestart {
            get {
                return ResourceManager.GetString("TitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GTA V is running! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleRunning {
            get {
                return ResourceManager.GetString("TitleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create shortcut? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleShortcut {
            get {
                return ResourceManager.GetString("TitleShortcut", resourceCulture);
            }
        }
    }
}
